name: Build mklittlefs

on:
  workflow_dispatch:  # Manually start a workflow

jobs:

  mklittlefs_build:
    runs-on: macos-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build mklittlefs
      run: |
        ./build_all_configs.sh
    - name: Release
      uses: jason2866/action-gh-release@v1.2
      with:
        tag_name: ${{ github.run_number }}
        prerelease: true
        files: |
            mklittlefs-*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}